{-# OPTIONS_GHC -Wno-unrecognised-pragmas #-}

{-# HLINT ignore "Redundant pure" #-}

module DSL.PMatch where

import Control.Monad.Except qualified as Except
import DSL.Cxt
import DSL.Cxt qualified as Cxt
import DSL.CxtUtils
import DSL.Database
import DSL.EvalTy
import DSL.PatUtils (matchOrReport)
import DSL.PrettyTy
import DSL.QuoteTy
import DSL.Types
import DSL.Utils
import DSL.Expr
import DSL.Pat qualified as P
import DSL.PrettyUtils (slistSep)
import Data.HashMap.Strict qualified as HashMap
import Data.HashSet qualified as HashSet
import Data.IntMap.Strict qualified as IntMap
import Data.List qualified as List
import Data.Maybe qualified as Maybe
import Data.Sequence qualified as Seq
import Data.Traversable
import Optics
import Prettyprinter qualified as PP
import Relude
import Utils.Misc
import Witherable

data PatData
  = PVar Name
  | PTuple [Pat]
  | PClass UID MemberID Pat
  | PLit Lit
  | PAs Name Pat
  | -- | The '_' in, e.g., '[Some _]'.
    -- This is also used as a placeholder for
    -- badly-written patterns from the user.
    PIgnored
  | -- A pattern that cannot be matched on. Typically used to substitute invalid
    -- patterns for error-tolerance.
    PUnmatchable
  deriving (Show)

data Pat = Pat
  { expr :: Expr
  -- ^ The origin expression
  , the :: PatData
  }
  deriving (Show)

-- | Tm value for pattern matching
data PVal
  = PVBound PatLvl
  | PVTuple [PVal]
  | PVClass UID MemberID PVal
  | PVLit Lit
  deriving (Show)

{- | @val : type_ IS pat?@

See https://julesjacobs.com/notes/patternmatching/patternmatching.pdf.
-}
data PMTest = PMTest
  { val :: PVal
  , pat :: Pat
  , type_ :: Vy
  }
  deriving (Show)

makeFieldLabelsNoPrefix ''PMTest

newtype PMLetMapping = PMLetMapping {unPMLetMapping :: [(Name, PatLvl)]}
  deriving newtype (Semigroup, Monoid)
  deriving (Show)

-- | Create a 'PMLetMapping' with a single binding.
pmLet :: Name -> PatLvl -> PMLetMapping
pmLet letName toPatLvl =
  PMLetMapping [(letName, toPatLvl)]

type PatScope = TmScope

data PMClause = PMClause
  { id :: MatchClauseID
  , tests :: [PMTest]
  , patScope :: PatScope
  , lets :: PMLetMapping
  -- ^ A list of 'let' bindings generated by the pattern of this clause.
  , hasGuard :: Bool
  }
  deriving (Show)
makeFieldLabelsNoPrefix ''PMClause

-- | A map of (PVarLvl -> PVal)
type PMSubstMap = IntMap PVal

data PMProblem = PMProblem
  { clauses :: [PMClause]
  , val :: PVal
  -- ^ The scrutinee of the current problem. Used for reporting to the user on
  -- unhandled cases.
  , history :: [(PVal, PMSubstMap)]
  -- ^ For debugging. The complete history of substitutions that led to the
  -- current problem. The oldest one is at the end of the list, and the most
  -- recent one is at the head.
  , dom :: PatLvl
  -- ^ The number of bound variables in the "context" of the current problem.
  -- Should be 1 for the initial problem, as 'PVBound 0' should point to the
  -- scrutinee.
  }
makeFieldLabelsNoPrefix ''PMProblem

data PMSimpMismatch = PMSimpMismatch
  deriving (Show, Eq)

data PMSimpTestResult = PMSimpTestResult
  { tests :: [PMTest]
  -- ^ The returned list of simplified tests.
  , lets :: PMLetMapping
  -- ^ If a test looks like @a IS y@, it is put here and popped out of the
  -- original clause.
  }

instance Semigroup PMSimpTestResult where
  PMSimpTestResult newTests1 bareTests1 <> PMSimpTestResult newTests2 bareTests2 =
    PMSimpTestResult (newTests1 <> newTests2) (bareTests1 <> bareTests2)

instance Monoid PMSimpTestResult where
  mempty = PMSimpTestResult [] mempty

-- * Prettying

newtype PrettyPValOptions = PrettyPValOptions
  { formatBound :: PatLvl -> PP.Doc Void
  -- ^ How to format bound variables. The argument is the 'PatLvl' of the bound
  -- variable.
  }

prettyPValOpt :: PrettyPValOptions -> PVal -> PP.Doc ann
prettyPValOpt opts = go
 where
  go :: PVal -> PP.Doc ann
  go = \case
    PVBound l -> do
      vacuous $ opts.formatBound l
    PVClass _ (MemberID memberID) value -> do
      slistSep ["%" <> PP.pretty memberID, go value]
    PVTuple fields -> do
      slistSep (";" : map go fields)
    PVLit lit -> do
      prettyLit lit

-- | A version of 'prettyPV for general purposes.
prettyPVal :: PVal -> PP.Doc ann
prettyPVal = prettyPValOpt opts
 where
  opts =
    PrettyPValOptions
      { formatBound = \l -> "#" <> PP.pretty l
      }

prettyPat :: Pat -> PP.Doc ann
prettyPat = goPat
 where
  goPat :: Pat -> PP.Doc ann
  goPat pat = case pat.the of
    PVar name -> do
      PP.pretty name
    PClass _ (MemberID memberID) value -> do
      slistSep ["%" <> PP.pretty memberID, prettyPat value]
    PTuple fields -> do
      slistSep (";" : map prettyPat fields)
    PLit lit -> do
      PP.viaShow lit
    PAs name pat -> do
      slistSep ["as", PP.pretty name, prettyPat pat]
    PIgnored -> do
      "<_>"
    PUnmatchable -> do
      "<unmatchable>"

prettyPMTest :: Cxt -> PMTest -> IO (PP.Doc ann)
prettyPMTest cxt test = do
  ty <- quoteTy (eval cxt) (scopeLvl cxt.tyScope) test.type_
  tyDoc <- prettyTy cxt.db (scopeNames cxt.tyScope) ty
  pure $
    prettyPVal test.val
      <> " IS "
      <> prettyPat test.pat
      <> " : "
      <> tyDoc

prettyPMLetMapping :: PMLetMapping -> PP.Doc ann
prettyPMLetMapping (PMLetMapping mapper) = do
  -- We sort on PValInt so the output looks less random and prettier
  let entries = List.sortOn snd mapper
  PP.list (entries <&> \(name, l) -> PP.pretty name <> " = #" <> PP.pretty l)

prettyPMClause :: Cxt -> PMClause -> IO (PP.Doc ann)
prettyPMClause cxt clause = do
  testDocs <- traverse (prettyPMTest cxt) clause.tests
  let letsDoc = prettyPMLetMapping clause.lets

  pure $
    PP.group $
      "Clause (ID="
        <> PP.pretty clause.id.unMatchClauseID
        <> "): "
        <> PP.list testDocs
        <> " => ... (lets: "
        <> letsDoc
        <> ")"

prettyPMProblem :: Cxt -> PMProblem -> IO (PP.Doc ann)
prettyPMProblem cxt prob = do
  clauseDocs <- for prob.clauses \clause -> do
    prettyPMClause cxt clause

  let
    historyDocs =
      zip [1 ..] (reverse prob.history) <&> \(i :: Int, (val, submap)) -> do
        let
          submapDocs =
            IntMap.toList submap <&> \(lvl, newval) ->
              "#" <> PP.pretty lvl <> " -> " <> prettyPVal newval
          submapDoc =
            if null submapDocs
              then ""
              else " (" <> PP.hsep (PP.punctuate "," submapDocs) <> ")"
        "- (STEP=" <> PP.pretty i <> ") case " <> prettyPVal val <> submapDoc

  pure $
    PP.vcat
      [ "Problem (dom = " <> show prob.dom <> "):"
      , PP.indent 1 $ PP.vcat historyDocs
      , PP.indent 2 $ if null clauseDocs then "<no clauses>" else PP.vcat clauseDocs
      ]

{- | Check the validity of pattern variables of a match case, and return the
pattern variable environment.

Also reports errors.
-}
checkPatternExpr ::
  Cxt ->
  -- | Scrutinee's type
  Vy ->
  -- | Pattern expression
  Expr ->
  -- | Pattern variable parameters generated by this pattern match case. The
  -- order of the pattern variables is the same as their appearance in the
  -- user's written pattern.
  IO (PatScope, Pat)
checkPatternExpr cxt scrutTy inPExpr = do
  patScopeRef <- newIORef (scopeNil :: PatScope)
  seenNameRef <- newIORef (HashSet.empty @Name)

  let
    makeErrorPattern :: Expr -> Vy -> PP.Doc Void -> IO Pat
    makeErrorPattern self patTy message = do
      patTyDoc <- cxtRenderVy cxt patTy
      scrutTyDoc <- cxtRenderVy cxt scrutTy
      Cxt.markExprError cxt self $ message <> "\nPattern type: " <> patTyDoc <> "\nRoot scrutinee type: " <> scrutTyDoc
      pure (Pat self PUnmatchable)

    -- Returns True if the name is not a duplicate, and False if it is a
    -- duplicate.
    registerPatternName :: (Expr, Name) -> Vy -> IO Bool
    registerPatternName (nameExpr, name) ty = do
      seenName <- readIORef seenNameRef

      if HashSet.member name seenName
        then do
          Cxt.markExprError cxt nameExpr $ "Duplicate pattern variable name: " <> PP.pretty name
          pure False
        else do
          modifyIORef' patScopeRef $ scopePush name ty
          pure True

    checkPat :: Expr -> Vy -> IO Pat
    checkPat patExpr patTy = do
      result <- matchOrReport cxt patExpr (patternAll patTy)
      case result of
        Nothing -> do
          makeErrorPattern patExpr patTy "Bad pattern expression"
        Just getPat -> do
          getPat

    patternAll :: Vy -> P.PExpr (IO Pat)
    patternAll patTy =
      -- NOTE: ORDER IS VERY IMPORTANT
      mconcat
        [ patternIgnored patTy
        , patternBool patTy
        , patternTuple patTy
        , patternAs patTy
        , patternClass patTy
        , patternVar patTy -- Must be placed last
        ]

    patternIgnored :: Vy -> P.PExpr (IO Pat)
    patternIgnored _patTy =
      P.capture (P.sym "_") <&> \(selfPat, ()) -> do
        pure (Pat selfPat PIgnored)

    patternTuple :: Vy -> P.PExpr (IO Pat)
    patternTuple patTy =
      P.block ";" $
        ( \elemPExprs P.BlockInfo{self} -> do
            patTy <- forceTyWeak (eval cxt) patTy
            asumL
              [ do
                  VyTuple elemTys <- pure patTy
                  guard $ length elemPExprs == length elemTys
                  lift do
                    elemPats <- for (zip elemPExprs (toList elemTys)) $ \(elemPExpr, elemTy) -> do
                      checkPat elemPExpr elemTy
                    pure $ Pat self (PTuple elemPats)
              ]
              (makeErrorPattern self patTy "Got [; ...] pattern but pattern type is not Tuple")
        )
          <$> P.manyItem P.anyExpr

    patternAs :: Vy -> P.PExpr (IO Pat)
    patternAs patTy =
      P.block "as" $
        ( \(nameExpr, name) patExpr block -> do
            ok <- registerPatternName (nameExpr, name) patTy
            if ok
              then do
                pat <- checkPat patExpr patTy
                pure (Pat block.self (PAs name pat))
              else do
                -- Skip the 'PAs' for error-tolerance.
                checkPat patExpr patTy
        )
          <$> P.item (P.label "<name>" (P.capture P.anySym))
          <*> P.item (P.label "<pat>" P.anyExpr)

    patternVar :: Vy -> P.PExpr (IO Pat)
    patternVar patTy =
      P.label "<name>" (P.capture P.anySym) <&> \(nameExpr, name) -> do
        ok <- registerPatternName (nameExpr, name) patTy
        -- Skip this 'PVar' for error-tolerance if necessary.
        pure (Pat nameExpr (if ok then PVar name else PIgnored))

    patternClass :: Vy -> P.PExpr (IO Pat)
    patternClass patTy =
      P.captures . P.list $
        ( \memberName valuePatExpr self -> do
            patTy <- forceTyWeak (eval cxt) patTy
            case patTy of
              VyRigid (VyClass uid) tyArgs -> do
                cls <- queryClass cxt.db uid
                case classMemberByName cls memberName of
                  Just member -> do
                    fieldTy <- evalTy (eval cxt) (envFromSp tyArgs) member.ty

                    -- Consider 'Maybe', if user types [Some] instead of [Some
                    -- value], then '[Some]' is treated as '[Some _]'.
                    valuePat <- case valuePatExpr of
                      Nothing -> do
                        pure (Pat self PIgnored)
                      Just valuePatExpr -> do
                        checkPat valuePatExpr fieldTy

                    pure (Pat self (PClass uid member.id valuePat))
                  _ -> do
                    makeErrorPattern self patTy $ "Unknown class member: " <> PP.pretty memberName
              _ -> do
                makeErrorPattern self patTy "Cannot use a rigid pattern here"
        )
          <$> P.item (P.label "<member>" P.anySym)
          <*> P.optionalItem (P.label "<pattern>" P.anyExpr)

    patternBool :: Vy -> P.PExpr (IO Pat)
    patternBool patTy =
      mconcat
        [ P.list (P.item (P.capture (P.sym "false"))) <&> handle False
        , P.list (P.item (P.capture (P.sym "true"))) <&> handle True
        ]
     where
      handle :: Bool -> (Expr, ()) -> IO Pat
      handle boolValue (self, ()) = do
        patTy <- forceTy (eval cxt) patTy
        case patTy of
          VyRigid (VyKnown KnownType'Bool) _ -> do
            pure (Pat self (PLit (LBool boolValue)))
          _ -> do
            makeErrorPattern self patTy "Must be of type Bool"

  pat <- checkPat inPExpr scrutTy
  patScope <- readIORef patScopeRef
  pure (patScope, pat)

-- * Pattern simplification

simpTest :: Cxt -> PMTest -> Except.ExceptT PMSimpMismatch IO PMSimpTestResult
simpTest cxt test = do
  let failSimp = Except.throwError PMSimpMismatch

  -- NOTE: We don't have to check the validity of patterns, since they
  -- should have already been checked during the 'checkPatternExpr' phase.
  type_ <- liftIO $ forceTyWeak (eval cxt) test.type_
  case (test.val, test.pat.the, type_) of
    (PVBound l, PVar pName, _type) -> do
      -- Bare constraint: Generate a new let-binding
      pure $ PMSimpTestResult [] (pmLet pName l)
    (_, PIgnored, _type) -> do
      -- Ignored pattern: We can drop everything, since PIgnored acts like a blackhole.
      pure mempty
    (PVBound l, PAs pName pat, _type) -> do
      -- As pattern: Hook into 'l' and then recurse.
      result <- simpTest cxt PMTest{val = test.val, pat, type_ = test.type_}
      pure $ PMSimpTestResult [] (pmLet pName l) <> result
    (_, PUnmatchable, _) -> do
      -- Unmatchable pattern
      failSimp
    (PVTuple vElems, PTuple pElems, VyTuple tElems) -> do
      -- Tuple pattern
      mconcat <$> for (zip3 vElems pElems (toList tElems)) \(v, p, t) -> do
        simpTest cxt (PMTest v p t)
    (PVClass _ vMemberID vValue, PClass _ pMemberID pValue, VyRigid (VyClass classUID) tyArgs) -> do
      unless (vMemberID == pMemberID) failSimp

      cls <- lift $ queryClass cxt.db classUID

      -- Must work. 'checkBranchRhs' should have already verified this.
      let member = Maybe.fromJust $ classMemberByID cls pMemberID

      valueTy <- lift $ evalTy (eval cxt) (envFromSp tyArgs) member.ty
      simpTest cxt (PMTest vValue pValue valueTy)
    (PVLit l1, PLit l2, _type) -> do
      -- Literal pattern.
      if l1 == l2 then pure mempty else failSimp
    _ -> do
      -- No more simplification rules apply to this constraint.
      pure (PMSimpTestResult [test] mempty)

simpTests :: Cxt -> [PMTest] -> Except.ExceptT PMSimpMismatch IO PMSimpTestResult
simpTests cxt tests = mconcat <$> traverse (simpTest cxt) tests

simpClause :: Cxt -> PMClause -> IO (Maybe PMClause)
simpClause cxt clause = do
  result <- Except.runExceptT $ simpTests cxt clause.tests
  case result of
    Left PMSimpMismatch -> do
      pure Nothing
    Right result -> do
      let
        clause' =
          clause
            & set #tests result.tests
            & over #lets (<> result.lets)
      pure $ Just clause'

simpProblem :: Cxt -> PMProblem -> IO PMProblem
simpProblem cxt prob = do
  -- Simplify clauses and drop ones that are impossible
  clauses <- wither (simpClause cxt) prob.clauses
  pure $ prob & set #clauses clauses

-- * Pattern variable substitution

substInPVal :: PMSubstMap -> PVal -> PVal
substInPVal submap subj = do
  case subj of
    PVBound l -> fromMaybe subj (IntMap.lookup l submap)
    _ -> subj

substInTest :: PMSubstMap -> PMTest -> PMTest
substInTest submap test = test & over #val (substInPVal submap)

substInClause :: PMSubstMap -> PMClause -> PMClause
substInClause submap clause = clause & over #tests (map (substInTest submap))

substInProb :: PMSubstMap -> PMProblem -> PMProblem
substInProb submap prob =
  prob
    & over #clauses (map (substInClause submap))
    & set #val val'
    & over #history ((val', submap) :)
 where
  val' = substInPVal submap prob.val

-- * Compile pattern matching

data PMUserClause = PMUserClause
  { pat :: Pat
  , patScope :: PatScope
  , guardTm :: Maybe Tm
  -- ^ Scoped under 'patScope'
  , bodyTm :: Tm
  -- ^ Scoped under 'patScope'
  }
  deriving (Show)

data CompilePatternMatchingParams = CompilePatternMatchingParams
  { scrutineeTm :: Tm
  -- ^ Scrutinee term
  , scrutineeTy :: Vy
  -- ^ Scrutinee type
  , userClauses :: [PMUserClause]
  -- ^ All branches ordered in user's written order.
  , scrutineeExpr :: Expr
  -- ^ For error-reporting.
  }

compilePatternMatching ::
  Cxt ->
  CompilePatternMatchingParams ->
  IO Tm
compilePatternMatching cxt CompilePatternMatchingParams{scrutineeTy = rootScrutTy, userClauses = userClausesIn, scrutineeExpr, scrutineeTm} = do
  -- See:
  --   1. https://jesper.sikanda.be/files/elaborating-dependent-copattern-matching.pdf
  --   2. https://compiler.club/compiling-pattern-matching/
  --   3. https://julesjacobs.com/notes/patternmatching/patternmatching.pdf

  -- ID all user clauses
  let userClauses = imap (\i userClause -> (MatchClauseID i, userClause)) userClausesIn

  let
    initProblem :: PMProblem
    initProblem =
      PMProblem
        { -- Should be 1 for the initial problem, as 'PVBound 0' should point to the scrutinee.
          dom = 1
        , -- Begin with #0, which points to the scrutinee. This will be expanded as we case split.
          val = PVBound 0
        , -- History starts with this for convenience.
          history = [(PVBound 0, mempty)]
        , clauses =
            userClauses <&> \(clauseID, userClause) -> do
              PMClause
                { id = clauseID
                , tests = [PMTest{val = PVBound 0, pat = userClause.pat, type_ = rootScrutTy}]
                , patScope = userClause.patScope
                , lets =
                    -- Nothing initially, but as we do case splitting, this will
                    -- be populated with the pattern variables generated from
                    -- the patterns of this clause.
                    mempty
                , hasGuard = isJust userClause.guardTm
                }
        }

  -- A set of clause IDs that have already been reached. If at the end some
  -- clause IDs are not reached, that means those clauses are redundant.
  reachedClauseIDSetRef <- newIORef (HashSet.empty @MatchClauseID)

  -- A list of problems that the user does not have clauses to handle.
  unhandledProblemsRef <- newIORef (Seq.empty @PMProblem)

  let
    markClauseReached :: MatchClauseID -> IO ()
    markClauseReached id = do
      modifyIORef' reachedClauseIDSetRef $ HashSet.insert id

    canSplitOnPat :: Pat -> Bool
    canSplitOnPat pat = case pat.the of
      PVar{} -> False -- We cannot split on '... = p'. It should be let-binded later.
      PIgnored{} -> False -- Same idea as PVar{} in spirit
      PAs _n pat -> canSplitOnPat pat
      _ ->
        -- We can split only on patterns like class members, literals, etc.
        True

    -- Returns the TmVar index and the type of the variable that we can case
    -- split on, if any.
    --
    -- Returns (The original pat for book-keeping, the TmVar index to split on,
    -- the type of the TmVar index)
    findSplitTarget :: [PMTest] -> Maybe (Pat, PatLvl, Vy)
    findSplitTarget = \case
      [] -> do
        Nothing
      (test : tests) -> do
        case (test.val, test.pat) of
          (PVBound l, pat) | canSplitOnPat pat -> do
            pure (test.pat, l, test.type_)
          _ -> do
            findSplitTarget tests

    -- Split on the given variable, and generate a MatchNode for it.
    --
    -- This function operates with 'solveProblem' to generate a match tree.
    caseSplit :: PMProblem -> (Pat, PatLvl, Vy) -> IO MatchNode
    caseSplit prob (originPat, scrLvl, scrTy) = do
      scrTy <- forceTyWeak (eval cxt) scrTy

      case scrTy of
        VyTuple elems -> do
          let numFields = length elems
          next <-
            solveProblem $
              prob
                & over #dom (+ numFields)
                & substInProb (IntMap.singleton scrLvl (PVTuple [PVBound l | l <- [prob.dom .. prob.dom + numFields - 1]]))
          pure . MatchNode'BranchTuple scrLvl $
            MatchBranchTuple
              { numFields = numFields
              , next = next
              }
        VyRigid (VyClass uid) _ -> do
          cls <- queryClass cxt.db uid
          MatchNode'BranchClass scrLvl <$> for (toList cls.members) \member -> do
            let pvValue = PVBound prob.dom
            next <-
              solveProblem $
                prob
                  & over #dom (+ 1)
                  & substInProb (IntMap.singleton scrLvl (PVClass uid member.id pvValue))
            pure
              MatchBranchClass
                { memberID = member.id
                , next = next
                }
        VyRigid (VyKnown KnownType'Bool) _ -> do
          MatchNode'BranchBool scrLvl <$> for [False, True] \boolValue -> do
            let prob' = prob & substInProb (IntMap.singleton scrLvl (PVLit (LBool boolValue)))
            next <- solveProblem prob'
            pure $ MatchBranchBool boolValue next
        _ -> do
          scrTyDoc <- cxtRenderVy cxt scrTy
          let msg = "Cannot split on type: " <> scrTyDoc

          Cxt.markExprError cxt originPat.expr msg

          pure $ MatchNode'LeafUnhandled

    solveProblem :: PMProblem -> IO MatchNode
    solveProblem prob = do
      prob <- simpProblem cxt prob
      case prob.clauses of
        [] -> do
          -- The user does not have a clause that handles this particular
          -- problem
          modifyIORef' unhandledProblemsRef (Seq.|> prob)
          pure MatchNode'LeafUnhandled
        (clause : restClauses) | null clause.tests -> do
          -- We hit a clause that this problem reaches
          markClauseReached clause.id

          let
            letMap = HashMap.fromList (unPMLetMapping clause.lets)
            patMap = scopeResolveMap clause.patScope
            patEnv =
              HashMap.intersectionWith (\patLvl (tmIx, _patTy) -> (tmIx, patLvl)) letMap patMap
                & HashMap.elems
                & envFromMap

          onGuardFail <-
            if clause.hasGuard
              then do
                let prob' = prob & set #clauses restClauses
                Just <$> solveProblem prob'
              else do
                pure Nothing

          pure . MatchNode'Leaf $
            MatchLeaf
              { targetClauseID = clause.id
              , patEnv = patEnv
              , onGuardFail = onGuardFail
              }

        -- Need to case split
        (clause : _otherClauses) -> do
          case findSplitTarget clause.tests of
            Nothing -> do
              panic "PMatch: Bad simplification. Did the simplification rules miss a case?"
            Just (originPat, targetLvl, targetType) -> do
              caseSplit prob (originPat, targetLvl, targetType)

  rootNode <- solveProblem initProblem

  -- Report errors / warnings
  unhandledProblems <- readIORef unhandledProblemsRef
  unless (null unhandledProblems) do
    let valDocs = unhandledProblems <&> \prob -> prettyPVal prob.val
    let outDoc = PP.vsep ("Scrutinee has unhandled case(s):" : toList valDocs)
    Cxt.markExprError cxt scrutineeExpr outDoc

  reachedClauseIDSet <- readIORef reachedClauseIDSetRef
  for_ userClauses \(clauseId, userClause) -> do
    unless (HashSet.member clauseId reachedClauseIDSet) do
      Cxt.markExprError cxt userClause.pat.expr "Unreachable/Redundant match pattern"

  -- Construct 'TmMatch'
  pure . TmMatch $
    MatchTree
      { scrutinee = scrutineeTm
      , root = rootNode
      , clauses =
          userClauses <&> \(clauseId, userClause) ->
            MatchClause
              { id = clauseId
              , patEnvLvl = scopeLvl userClause.patScope
              , bodyTm = userClause.bodyTm
              , guardTm = userClause.guardTm
              }
      }
